name: Deploy to PROD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to PROD EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/ubuntu/multi-env-devops-nodejs/app
            git pull origin main

            docker build -t myapp:prod .
            docker stop prod-app || true
            docker rm prod-app || true

            docker run -d \
              --name prod-app \
              --env-file /home/ubuntu/.env.prod \
              -p 3000:3000 \
              myapp:prod
#pavan
